### ISSUE TITLE
Cannot change ownership to uid 1000, gid 1000: Invalid argument

### ISSUE THREAD

**Issue by Dutchglory** [flathub/com.dropbox.Client#341] opened 2024-04-11 13:40 UTC
im getting  "Cannot change ownership to uid 1000, gid 1000: Invalid argument"  during installation as root ...

full list: 
[dropbox.txt](https://github.com/flathub/com.dropbox.Client/files/14946818/dropbox.txt)

**Comment by wjt** [comment] 2024-04-11 13:41
Duplicate of #122

**Closed by wjt** 2024-04-11 13:41 UTC
